---
title: Security-Tricks.com
email: security-tricks@protonmail.com
description: ''
baseurl: security-tricks.com
url: http://www.security-tricks.com
twitter_username: security-tricks
github_username: security-tricks
markdown: kramdown
theme: minima
gems:
- jekyll-feed
- jekyll-admin
exclude:
- Gemfile
- Gemfile.lock
