---
title: Security-Tricks.com
email: c2VjdXJpdHktdGlwc0Bwcm90b25tYWlsLmNvbQ==
description: ''
baseurl:
url:
twitter_username: security-tricks
github_username: security-tricks
markdown: kramdown
theme: minima
gems:
- jekyll-feed
- jekyll-admin
exclude:
- Gemfile
- Gemfile.lock
