---
title: Security-Tricks.com
email: 115 101 99 117 114 105 116 121 45 116 105 112 115 64 112 114 111 116 111 110 109 97 105 108 46 99 111 109
description: ''
baseurl:
url:
twitter_username: security-tricks
github_username: security-tricks
markdown: kramdown
theme: minima
gems:
- jekyll-feed
- jekyll-admin
exclude:
- Gemfile
- Gemfile.lock
